Added sorting layers control
BrianCraig/Tilemap-Shadow-Caster pull request #1
Opened 2021-04-06 20:24 UTC by reesvarney

This should allow anybody using this to apply the shadow caster to certain sorting layers rather than always going to all, personally I was using the sorting layers to apply shadows differently to objects and this wasn't possible - creating very harsh shadows.

I'm new to C# and unity so it may not be the most efficient however it seems operational. You may still want to change some parts such as the defaults as I think it will be "nothing" unless layers are selected by the user (I don't know how to do this myself).

2021-04-06 20:37 UTC, reesvarney commented
I have just noticed that whilst it seems to retain its value and is functional, it resets the appearance on the dropdown back to nothing when previewing the game. I assume this is something to do with serialisation and I'll take a look into it.

2021-04-06 23:20 UTC, reesvarney commented
Has been fixed by moving the calculation of layers into the runtime script. Only issue that might occur now would be the script not updating to match changes to the sorting layers.

2021-04-26 22:50 UTC, BrianCraig commented
@reesvarney Hi! Sorry i didn't noticed the PR! I'll check in between 24hrs!

2021-04-29 09:16 UTC, BrianCraig commented
@reesvarney Cool! Thanks for contributing!
Im going to add a readme to give more info and reference the [New example](https://github.com/BrianCraig/Tilemap-Shadow-Caster-Example), the code looks really good, don't mind i'm new into c# unity Editor coding also.

I added a non-breaking review, if you don't have time i'll accept the PR and change it after.

Brian

2021-04-29 09:17 UTC, BrianCraig requested changes

2021-04-29 09:17 UTC, BrianCraig commented on Editor/TilemapShadowCaster2DEditor.cs
> +        private static int flags;
flags, options and values are never used (here and OnEnable)

2021-04-29 10:21 UTC, reesvarney commented on Editor/TilemapShadowCaster2DEditor.cs
> +        private static int flags;
Ah, I forgot to remove flags/ values as I was previously calculating the bitmask from the editor script. However, I think `options` needs to stay to create the maskfield in `OnInspectorGUI`:
```csharp
 int newVal = EditorGUILayout.MaskField("Apply to sorting layers", m_ApplyToSortingLayersProperty.intValue, options)
 ```

2021-04-29 11:32 UTC, BrianCraig approved these changes

2021-04-29 11:32 UTC, merged

2021-04-29 11:32 UTC, BrianCraig commented
Cool, Thanks!